name: CI
on:
  push:
    branches: [main]
  pull_request: {}
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Test
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: "1.22"
      - run: go test -coverprofile=coverage.txt -covermode=atomic ./...
      - uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
